[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
nom = "7"
itertools = "0.13"
rayon = "1.10.0"
rustc-hash = "2.1.0"
raqote = { version = "0.8.5", default-features = false, features = ["png"]}
